name: Hello CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step A: Download your code onto the runner
      - name: Checkout code
        uses: actions/checkout@v4

      # Step B: Run the test script
      - name: Run Python Tests
        run: python3 test_calc.py
